Updated dockerfiles

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -1,7 +1,16 @@
 ###############
 # BUILD IMAGES #
 ###############
-FROM python:3.10
+FROM python:3.10 as builder
+
+RUN set -ex \
+    # Upgrade the package index and install security upgrades
+    && apt-get update \
+    && apt-get upgrade -y \
+    # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
 
 # Set the working directory
 WORKDIR /app
@@ -10,7 +19,7 @@ WORKDIR /app
 RUN rm -rvf /usr/local/lib/python3.10/site-packages/pip-23.0.1.dist-info
 
 # Upgrade pip to a specific version
-RUN pip install --upgrade pip==23.3
+RUN pip install --upgrade pip==24.0
 
 # Copy the requirements file into the container
 COPY requirements.txt .
@@ -18,30 +27,51 @@ COPY requirements.txt .
 # Install the requirements
 RUN pip install --no-cache-dir -r requirements.txt
 
-# Copy the rest of the application code into the container
-COPY . /app
-
-#Collect Static Files
-# RUN python manage.py collectstatic
+# Clean up
+RUN set -ex \
+    apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
 
 ###############
 # FINAL IMAGE #
 ###############
-
 FROM python:3.10-slim
 
-# Copy Binary files from the BASE Image
-COPY --from=builder /app /app
-COPY --from=builder /usr /usr
+# Set the working directory
+WORKDIR /app
 
-# create the app user
+# Copy the rest of the application code into the container
+COPY . .
+
+# Copy Binary files from the BASE Image
+# COPY --from=builder /usr/ /usr/
+
+# Copy Python libraries from the BASE Image
+COPY --from=builder /usr/local/lib/python3.10/ /usr/local/lib/python3.10/
+COPY --from=builder /usr/local/bin/uwsgi  /usr/local/bin/uwsgi
+# RUN set -ex \
+#     # Create a non-root user
+#     && addgroup --system --gid 1001 appgroup \
+#     && adduser --system --uid 1001 --gid 1001 --no-create-home python \
 RUN addgroup --system python && adduser --system --group python
+
+# Install uWSGI
+RUN pip install uwsgi
+
+# Install additional Python packages and uWSGI-related packages
+RUN set -ex \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends \
+        libxml2-dev \
+        libssl-dev \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
+    
+# Change ownership of the app directory to the python user
 RUN chown -R python:python /app
 
-# Migration
-# RUN python manage.py makemigrations && python manage.py migrate
-
-# change to the python user
+# Switch to the python user
 USER python
 
 # Expose port 7000 for the Django app
